# Numpy

## Задачи для совместного разбора

In [2]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [8]:
arr = np.random.uniform(low=0, high=20, size=(4, 7))
arr2 = np.random.uniform(low=0, high=20, size=(4, 7))

In [9]:
(arr - arr.min())/(arr.max() - arr.min())

array([[0.09951374, 0.95147555, 0.1276965 , 1.        , 0.51416003,
        0.56286273, 0.85986539],
       [0.34722868, 0.2852931 , 0.48867423, 0.21696689, 0.17064513,
        0.13259768, 0.        ],
       [0.27590066, 0.57929029, 0.33237398, 0.10944386, 0.95387329,
        0.8719987 , 0.89377342],
       [0.80316309, 0.64993696, 0.46677175, 0.14843062, 0.16634609,
        0.58846947, 0.59282734]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [18]:
arr = np.random.randint(low=0, high=10, size=(8, 10))
arr

array([[3, 8, 6, 8, 4, 7, 6, 8, 1, 4],
       [7, 9, 2, 2, 3, 0, 8, 9, 6, 0],
       [3, 1, 2, 8, 2, 4, 7, 9, 8, 8],
       [5, 2, 5, 1, 8, 3, 5, 6, 7, 7],
       [0, 1, 7, 1, 2, 4, 2, 6, 2, 9],
       [9, 7, 2, 7, 9, 9, 9, 6, 3, 8],
       [5, 6, 6, 9, 9, 9, 4, 1, 5, 5],
       [7, 4, 7, 0, 1, 2, 5, 4, 1, 0]])

In [30]:
sum_by_row = arr.sum(axis=1)
min_idx = sum_by_row.argmin()
min_idx, arr[min_idx]

(7, array([7, 4, 7, 0, 1, 2, 5, 4, 1, 0]))

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [33]:
x = np.array([1, 2, 3])
y = np.array([1, 4, 3])

np.sqrt(np.power(x-y, 2).sum())

2.0

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [35]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

In [44]:
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
X

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

In [52]:
s = A @ X @ B
print(s, -C)

[[ -7. -21.]
 [-11.  -8.]
 [ -8.  -4.]] [[ -7 -21]
 [-11  -8]
 [ -8  -4]]


## Лабораторная работа №1

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

In [ ]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [43]:
fname = 'minutes_n_ingredients.csv'
data = np.loadtxt(fname, dtype='int32', delimiter = ",", comments="id,minutes,n_ingredients")

print("Первые 5 строк: ", data[:5])

Первые 5 строк:  [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [44]:
first_d = {'min': min(data[:, 0]), 'max': max(data[:, 0]), 'med': np.median(data[:, 0])}
second_d = {'min': min(data[:, 1]), 'max': max(data[:, 1]), 'med': np.median(data[:, 1])}
print("Минимум, максимум и медиана по каждому из столбцов: ", first_d, second_d)

Минимум, максимум и медиана по каждому из столбцов:  {'min': 38, 'max': 537671, 'med': 207193.5} {'min': 0, 'max': 2147483647, 'med': 40.0}


3. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [45]:
nums = np.random.randint(0, len(data), size=10)
print("информация 0 19 различных рецептах: ", data[nums])

информация 0 19 различных рецептах:  [[127974     25      6]
 [378291     24     12]
 [429195     30     21]
 [519467    130      7]
 [184588     23      9]
 [ 55957     10      5]
 [206357     30     10]
 [ 89844    260      8]
 [ 17403     20      9]
 [211313     40      5]]


4. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [46]:
chk = data[:, 2]<=5
data_new = data[chk]
print("Новая версия массива в котором не более 5 ингредиентов: ", data_new)

Новая версия массива в котором не более 5 ингредиентов:  [[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


5. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [47]:
mean_amount = np.mean(data[:, 2])
less_than_mean = data[:, 2]<mean_amount

print("Процент рецептов, количество ингредиентов в которых меньше среднего: ", 100 * len(data[less_than_mean])/len(data), '%')

Процент рецептов, количество ингредиентов в которых меньше среднего:  58.802 %


6. Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [48]:
q_075 = np.quantile(data[:, 1], 0.75)
data[:, 1] = np.clip(data[:, 1], np.min(data[:, 1]), q_075)
print("Скорректированный массив с учетом 0,75 квантиля: ", data)

Скорректированный массив с учетом 0,75 квантиля:  [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


7. Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [49]:
chk = data[:, 1]==0
amount = len(data[chk])
data[:, 1] = np.clip(data[:, 1], 1, q_075)

print('Кол-во нулей =', amount)
print("Массив в котором нули заменены на единицы: ", data)

Кол-во нулей = 479
Массив в котором нули заменены на единицы:  [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


8. Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [50]:
uniq, counts = np.unique(data[:, 2], return_counts=True)
condition = np.isin(np.arange(1, 42), uniq) == False

print("Уникальные элементы и количество их вхождений: ", np.asarray((uniq, counts)).T)
print('Отсутствие: ', np.arange(1, 42)[condition])

Уникальные элементы и количество их вхождений:  [[    1    13]
 [    2   926]
 [    3  2895]
 [    4  5515]
 [    5  7913]
 [    6  9376]
 [    7 10628]
 [    8 10951]
 [    9 10585]
 [   10  9591]
 [   11  8297]
 [   12  6605]
 [   13  4997]
 [   14  3663]
 [   15  2595]
 [   16  1767]
 [   17  1246]
 [   18   790]
 [   19   573]
 [   20   376]
 [   21   217]
 [   22   161]
 [   23   105]
 [   24    69]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]
Отсутствие:  [36 38 40 41]


9. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [51]:
ingr_min = data[:, 2]/data[:, 1]
print("Количество ингредиентов приходящихся на минуту рецепта: ", ingr_min)
print("Масимальное значение Количество ингредиентов/минута: ", np.max(ingr_min))

Количество ингредиентов приходящихся на минуту рецепта:  [0.26666667 0.28       0.6        ... 0.23076923 0.8        0.21538462]
Масимальное значение Количество ингредиентов/минута:  24.0


10. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [52]:
cond_20min = data[:, 1]<=20
cond_5ing = data[:, 2]<=5

main_condition = cond_20min * cond_5ing
main_condition = np.array(main_condition, dtype='int')
data = np.insert(data, 3, main_condition, axis=1)
print("Измененный массив: ", data)

Измененный массив:  [[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


11. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [53]:
arr = np.random.randint(0, 100, size=(100000, 3))
arr

array([[ 2,  7, 74],
       [93, 53, 97],
       [77, 68, 16],
       ...,
       [67, 72, 99],
       [41, 29, 72],
       [ 8, 42, 29]])

In [56]:
short = arr[arr[:,1]<10]
short.shape

(9954, 3)

In [57]:
standart = arr[(arr[:,1]>=10) & (arr[:,1]<20)]
standart.shape

(9949, 3)

In [58]:
long = arr[arr[:,1]>=20]
long.shape

(80097, 3)

In [59]:
lenght = min(len(short), len(standart), len(long))
lenght

9949

In [62]:
arr = np.stack([short[:lenght], standart[:lenght], long[:lenght]])
arr.shape

(3, 9949, 3)

In [63]:
arr[2]

array([[93, 53, 97],
       [77, 68, 16],
       [31, 58, 17],
       ...,
       [35, 21, 17],
       [ 0, 96, 56],
       [14, 91, 23]])